const SPECIALTY_ROUTE_PATHS = {
  ROOT: '/',
  ADMIN_ROOT: '/admin',
  DETAIL: '/:id',
};

const SPECIALTY_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SPECIALTY_NOT_FOUND: 'SPECIALTY_NOT_FOUND',
  SPECIALTY_ALREADY_EXISTS: 'SPECIALTY_ALREADY_EXISTS',
  SPECIALTY_SLUG_ALREADY_EXISTS: 'SPECIALTY_SLUG_ALREADY_EXISTS',
  SPECIALTY_IN_USE: 'SPECIALTY_IN_USE',
  LIST_SPECIALTIES_FAILED: 'LIST_SPECIALTIES_FAILED',
  GET_SPECIALTY_FAILED: 'GET_SPECIALTY_FAILED',
  CREATE_SPECIALTY_FAILED: 'CREATE_SPECIALTY_FAILED',
  UPDATE_SPECIALTY_FAILED: 'UPDATE_SPECIALTY_FAILED',
  DELETE_SPECIALTY_FAILED: 'DELETE_SPECIALTY_FAILED',
};

const SPECIALTY_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

module.exports = {
  SPECIALTY_ROUTE_PATHS,
  SPECIALTY_ERROR_CODES,
  SPECIALTY_PAGINATION,
};
