const SCHEDULE_ROUTE_PATHS = {
  ROOT: '/',
  BY_DOCTOR: '/doctor/:doctorId',
};

const SCHEDULE_ERROR_CODES = {
  VALIDATION_ERROR: 'SCHEDULE_VALIDATION_ERROR',
  DOCTOR_NOT_FOUND: 'SCHEDULE_DOCTOR_NOT_FOUND',
  SCHEDULE_ALREADY_EXISTS: 'SCHEDULE_ALREADY_EXISTS',
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  INVALID_DATE_RANGE: 'SCHEDULE_INVALID_DATE_RANGE',
  INVALID_WEEKDAYS: 'SCHEDULE_INVALID_WEEKDAYS',
  INVALID_SHIFTS: 'SCHEDULE_INVALID_SHIFTS',
  PAST_WORKING_DATE: 'SCHEDULE_PAST_WORKING_DATE',
  EMPTY_BATCH_RANGE: 'SCHEDULE_EMPTY_BATCH_RANGE',
  CREATE_SCHEDULE_FAILED: 'CREATE_SCHEDULE_FAILED',
  LIST_SCHEDULES_FAILED: 'LIST_SCHEDULES_FAILED',
  GET_DOCTOR_SCHEDULES_FAILED: 'GET_DOCTOR_SCHEDULES_FAILED',
};

const SCHEDULE_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 1000,
};

const SCHEDULE_VIEWS = {
  DAY: 'DAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
};

const WORKING_SHIFTS = {
  MORNING: 'MORNING',
  AFTERNOON: 'AFTERNOON',
};

const SHIFT_TIME_WINDOWS = {
  MORNING: {
    start: '08:00',
    end: '11:30',
  },
  AFTERNOON: {
    start: '13:30',
    end: '17:00',
  },
};

const SCHEDULE_STATUSES = {
  WORKING: 'WORKING',
  APPROVED_OFF: 'APPROVED_OFF',
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
};

const SLOT_DURATION_MINUTES = 30;
const VALID_WEEKDAYS = [0, 1, 2, 3, 4, 5, 6];

module.exports = {
  SCHEDULE_ROUTE_PATHS,
  SCHEDULE_ERROR_CODES,
  SCHEDULE_PAGINATION,
  SCHEDULE_VIEWS,
  WORKING_SHIFTS,
  SHIFT_TIME_WINDOWS,
  SCHEDULE_STATUSES,
  SLOT_DURATION_MINUTES,
  VALID_WEEKDAYS,
};
