version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:9.0.0
    container_name: careplus-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: careplus
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: careplus-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Restrict memory for local dev
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: careplus-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
