const DOCTOR_ROUTE_PATHS = {
  ROOT: '/',
  ME_PROFILE: '/me/profile',
  ME_DASHBOARD: '/me/dashboard',
  BY_ID: '/:id',
  PRICE: '/:id/price',
};

const DOCTOR_ERROR_CODES = {
  VALIDATION_ERROR: 'DOCTOR_VALIDATION_ERROR',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  DOCTOR_PROFILE_NOT_FOUND: 'DOCTOR_PROFILE_NOT_FOUND',
  LIST_DOCTORS_FAILED: 'LIST_DOCTORS_FAILED',
  GET_DOCTOR_FAILED: 'GET_DOCTOR_FAILED',
  GET_MY_DOCTOR_PROFILE_FAILED: 'GET_MY_DOCTOR_PROFILE_FAILED',
  UPDATE_MY_DOCTOR_PROFILE_FAILED: 'UPDATE_MY_DOCTOR_PROFILE_FAILED',
  UPDATE_DOCTOR_PRICE_FAILED: 'UPDATE_DOCTOR_PRICE_FAILED',
  UPDATE_DOCTOR_PROFILE_FAILED: 'UPDATE_DOCTOR_PROFILE_FAILED',
  INVALID_DOCTOR_PRICE: 'INVALID_DOCTOR_PRICE',
  DOCTOR_DASHBOARD_FAILED: 'DOCTOR_DASHBOARD_FAILED',
};

const DOCTOR_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

module.exports = {
  DOCTOR_ROUTE_PATHS,
  DOCTOR_ERROR_CODES,
  DOCTOR_PAGINATION,
};
