const APPOINTMENT_ROUTE_PATHS = {
  ROOT: '/',
  MY: '/my',
  MY_DETAIL: '/my/:id',
  MY_CANCEL: '/my/:id/cancel',
  DOCTOR_ME: '/doctor/me',
  DOCTOR_ME_STATUS: '/doctor/me/:id/status',
  RECEPTIONIST_BOOK: '/receptionist',
  RECEPTIONIST_PATIENTS: '/receptionist/patients',
  DETAIL: '/:id',
  STATUS: '/:id/status',
};

const APPOINTMENT_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_FORBIDDEN: 'APPOINTMENT_FORBIDDEN',
  SLOT_NOT_FOUND: 'SLOT_NOT_FOUND',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_LOCKED: 'PATIENT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  MAX_NO_SHOW_REACHED: 'MAX_NO_SHOW_REACHED',
  MAX_ACTIVE_APPOINTMENTS_REACHED: 'MAX_ACTIVE_APPOINTMENTS_REACHED',
  SAME_DAY_BOOKING_EXISTS: 'SAME_DAY_BOOKING_EXISTS',
  ACTIVE_BOOKING_WITH_DOCTOR_EXISTS: 'ACTIVE_BOOKING_WITH_DOCTOR_EXISTS',
  CANCELLATION_LIMIT_EXCEEDED: 'CANCELLATION_LIMIT_EXCEEDED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  CREATE_APPOINTMENT_FAILED: 'CREATE_APPOINTMENT_FAILED',
  CANCEL_APPOINTMENT_FAILED: 'CANCEL_APPOINTMENT_FAILED',
  UPDATE_STATUS_FAILED: 'UPDATE_STATUS_FAILED',
  LIST_APPOINTMENTS_FAILED: 'LIST_APPOINTMENTS_FAILED',
  SEARCH_PATIENTS_FAILED: 'SEARCH_PATIENTS_FAILED',
  PATIENT_PROFILE_NOT_FOUND: 'PATIENT_PROFILE_NOT_FOUND',
  PATIENT_PROFILE_FORBIDDEN: 'PATIENT_PROFILE_FORBIDDEN',
};

const APPOINTMENT_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const APPOINTMENT_STATUSES = {
  CONFIRMED: 'CONFIRMED',
  CHECKED_IN: 'CHECKED_IN',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
};

const BOOKING_CHANNELS = {
  ONLINE: 'ONLINE',
  RECEPTION: 'RECEPTION',
};

const BOOKING_SOURCES = {
  PATIENT_WEB: 'PATIENT_WEB',
  RECEPTIONIST: 'RECEPTIONIST',
};

const VALID_APPOINTMENT_STATUSES = Object.values(APPOINTMENT_STATUSES);
const VALID_BOOKING_CHANNELS = Object.values(BOOKING_CHANNELS);
const VALID_BOOKING_SOURCES = Object.values(BOOKING_SOURCES);

module.exports = {
  APPOINTMENT_ROUTE_PATHS,
  APPOINTMENT_ERROR_CODES,
  APPOINTMENT_PAGINATION,
  APPOINTMENT_STATUSES,
  BOOKING_CHANNELS,
  BOOKING_SOURCES,
  VALID_APPOINTMENT_STATUSES,
  VALID_BOOKING_CHANNELS,
  VALID_BOOKING_SOURCES,
};
