const CLINIC_SETTINGS_ROUTE_PATHS = {
  CLINIC_INFO: '/clinic-info',
  SYSTEM: '/system',
};

const CLINIC_SETTINGS_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CLINIC_INFO_NOT_FOUND: 'CLINIC_INFO_NOT_FOUND',
  GET_CLINIC_INFO_FAILED: 'GET_CLINIC_INFO_FAILED',
  UPDATE_CLINIC_INFO_FAILED: 'UPDATE_CLINIC_INFO_FAILED',
  SYSTEM_SETTING_NOT_FOUND: 'SYSTEM_SETTING_NOT_FOUND',
  GET_SYSTEM_SETTING_FAILED: 'GET_SYSTEM_SETTING_FAILED',
  UPDATE_SYSTEM_SETTING_FAILED: 'UPDATE_SYSTEM_SETTING_FAILED',
};

const CLINIC_SETTINGS_DEFAULTS = {
  MAX_BOOKING_DAYS_AHEAD: 7,
  SLOT_DURATION_MINUTES: 30,
  CANCEL_BEFORE_HOURS: 2,
  MAX_NO_SHOW_BEFORE_LOCK: 3,
  MORNING_SHIFT_START: '08:00',
  MORNING_SHIFT_END: '11:30',
  AFTERNOON_SHIFT_START: '13:30',
  AFTERNOON_SHIFT_END: '17:00',
};

const SYSTEM_SETTING_LIMITS = {
  MIN_MAX_BOOKING_DAYS_AHEAD: 1,
  MIN_SLOT_DURATION_MINUTES: 1,
  MIN_CANCEL_BEFORE_HOURS: 0,
  MIN_MAX_NO_SHOW_BEFORE_LOCK: 1,
};

module.exports = {
  CLINIC_SETTINGS_ROUTE_PATHS,
  CLINIC_SETTINGS_ERROR_CODES,
  CLINIC_SETTINGS_DEFAULTS,
  SYSTEM_SETTING_LIMITS,
};
