const USER_ROUTE_PATHS = {
  ROOT: '/',
  ME: '/me',
  STATUS: '/:id/status',
  RESET_NO_SHOW: '/:id/reset-no-show',
};

const USER_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CANNOT_UPDATE_OWN_STATUS: 'CANNOT_UPDATE_OWN_STATUS',
  CANNOT_RESET_OWN_NO_SHOW: 'CANNOT_RESET_OWN_NO_SHOW',
  INVALID_USER_STATUS: 'INVALID_USER_STATUS',
  LIST_USERS_FAILED: 'LIST_USERS_FAILED',
  GET_ME_FAILED: 'GET_ME_FAILED',
  UPDATE_ME_FAILED: 'UPDATE_ME_FAILED',
  UPDATE_USER_STATUS_FAILED: 'UPDATE_USER_STATUS_FAILED',
  RESET_NO_SHOW_FAILED: 'RESET_NO_SHOW_FAILED',
};

const USER_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const USER_STATUSES = {
  ACTIVE: 'ACTIVE',
  LOCKED: 'LOCKED',
};

const VALID_USER_STATUSES = Object.values(USER_STATUSES);

module.exports = {
  USER_ROUTE_PATHS,
  USER_ERROR_CODES,
  USER_PAGINATION,
  USER_STATUSES,
  VALID_USER_STATUSES,
};
