const USER_ROUTE_PATHS = {
  ROOT: '/',
  ME: '/me',
  ME_PASSWORD: '/me/password',
  STAFF: '/staff',
  DETAIL: '/:id',
  STATUS: '/:id/status',
  RESET_NO_SHOW: '/:id/reset-no-show',
};

const USER_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_STAFF_ROLE: 'INVALID_STAFF_ROLE',
  CANNOT_UPDATE_OWN_STATUS: 'CANNOT_UPDATE_OWN_STATUS',
  CANNOT_RESET_OWN_NO_SHOW: 'CANNOT_RESET_OWN_NO_SHOW',
  INVALID_USER_STATUS: 'INVALID_USER_STATUS',
  CREATE_STAFF_USER_FAILED: 'CREATE_STAFF_USER_FAILED',
  LIST_USERS_FAILED: 'LIST_USERS_FAILED',
  GET_USER_DETAIL_FAILED: 'GET_USER_DETAIL_FAILED',
  GET_ME_FAILED: 'GET_ME_FAILED',
  UPDATE_ME_FAILED: 'UPDATE_ME_FAILED',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  NEW_PASSWORD_SAME_AS_OLD: 'NEW_PASSWORD_SAME_AS_OLD',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',
  ADMIN_UPDATE_USER_FAILED: 'ADMIN_UPDATE_USER_FAILED',
  UPDATE_USER_STATUS_FAILED: 'UPDATE_USER_STATUS_FAILED',
  RESET_NO_SHOW_FAILED: 'RESET_NO_SHOW_FAILED',
};

const USER_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const USER_STATUSES = {
  ACTIVE: 'ACTIVE',
  LOCKED: 'LOCKED',
};

const VALID_USER_STATUSES = Object.values(USER_STATUSES);

const STAFF_CREATABLE_ROLES = ['DOCTOR', 'RECEPTIONIST', 'ADMIN'];

module.exports = {
  USER_ROUTE_PATHS,
  USER_ERROR_CODES,
  USER_PAGINATION,
  USER_STATUSES,
  VALID_USER_STATUSES,
  STAFF_CREATABLE_ROLES,
};
