const PATIENT_PROFILE_ROUTE_PATHS = {
  ROOT: '/',
  SET_DEFAULT: '/:id/default',
  DETAIL: '/:id',
};

const PATIENT_PROFILE_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PATIENT_PROFILE_NOT_FOUND: 'PATIENT_PROFILE_NOT_FOUND',
  PATIENT_PROFILE_INACTIVE: 'PATIENT_PROFILE_INACTIVE',
  PROFILE_HAS_ACTIVE_APPOINTMENT: 'PROFILE_HAS_ACTIVE_APPOINTMENT',
  PATIENT_PROFILE_FORBIDDEN: 'PATIENT_PROFILE_FORBIDDEN',
  CREATE_PATIENT_PROFILE_FAILED: 'CREATE_PATIENT_PROFILE_FAILED',
  UPDATE_PATIENT_PROFILE_FAILED: 'UPDATE_PATIENT_PROFILE_FAILED',
  DELETE_PATIENT_PROFILE_FAILED: 'DELETE_PATIENT_PROFILE_FAILED',
  SET_DEFAULT_PROFILE_FAILED: 'SET_DEFAULT_PROFILE_FAILED',
  LIST_PATIENT_PROFILES_FAILED: 'LIST_PATIENT_PROFILES_FAILED',
  GET_PATIENT_PROFILE_FAILED: 'GET_PATIENT_PROFILE_FAILED',
};

const PATIENT_PROFILE_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const PATIENT_PROFILE_GENDERS = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
};

const PATIENT_PROFILE_RELATIONSHIPS = {
  SELF: 'SELF',
  CHA: 'CHA',
  ME: 'ME',
  CON: 'CON',
  VO: 'VO',
  CHONG: 'CHONG',
  ANH: 'ANH',
  CHI: 'CHI',
  EM: 'EM',
  ONG: 'ONG',
  BA: 'BA',
  KHAC: 'KHAC',
};

const VALID_PATIENT_PROFILE_GENDERS = Object.values(PATIENT_PROFILE_GENDERS);
const VALID_PATIENT_PROFILE_RELATIONSHIPS = Object.values(PATIENT_PROFILE_RELATIONSHIPS);

module.exports = {
  PATIENT_PROFILE_ROUTE_PATHS,
  PATIENT_PROFILE_ERROR_CODES,
  PATIENT_PROFILE_PAGINATION,
  PATIENT_PROFILE_GENDERS,
  PATIENT_PROFILE_RELATIONSHIPS,
  VALID_PATIENT_PROFILE_GENDERS,
  VALID_PATIENT_PROFILE_RELATIONSHIPS,
};
