const REVIEW_ROUTE_PATHS = {
  ROOT: '/',
  DOCTOR_REVIEWS: '/doctor/:doctorId',
  APPOINTMENT_REVIEW: '/appointment/:appointmentId',
};

const REVIEW_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_NOT_COMPLETED: 'APPOINTMENT_NOT_COMPLETED',
  UNAUTHORIZED_REVIEWER: 'UNAUTHORIZED_REVIEWER',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  CREATE_REVIEW_FAILED: 'CREATE_REVIEW_FAILED',
  GET_REVIEWS_FAILED: 'GET_REVIEWS_FAILED',
};

const REVIEW_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 5,
  MAX_LIMIT: 50,
};

module.exports = {
  REVIEW_ROUTE_PATHS,
  REVIEW_ERROR_CODES,
  REVIEW_PAGINATION,
};
