const APPROVAL_REQUEST_ROUTE_PATHS = {
  ROOT: '/',
  SCHEDULE_EXCEPTION: '/schedule-exception',
  APPROVE: '/:id/approve',
  REJECT: '/:id/reject',
};

const APPROVAL_REQUEST_ERROR_CODES = {
  VALIDATION_ERROR: 'APPROVAL_REQUEST_VALIDATION_ERROR',
  DOCTOR_NOT_FOUND: 'APPROVAL_REQUEST_DOCTOR_NOT_FOUND',
  REQUEST_NOT_FOUND: 'APPROVAL_REQUEST_NOT_FOUND',
  ACTIVE_REQUEST_ALREADY_EXISTS: 'APPROVAL_REQUEST_ACTIVE_REQUEST_ALREADY_EXISTS',
  INVALID_REQUEST_STATUS: 'APPROVAL_REQUEST_INVALID_STATUS',
  CREATE_REQUEST_FAILED: 'APPROVAL_REQUEST_CREATE_FAILED',
  LIST_REQUESTS_FAILED: 'APPROVAL_REQUEST_LIST_FAILED',
  APPROVE_REQUEST_FAILED: 'APPROVAL_REQUEST_APPROVE_FAILED',
  REJECT_REQUEST_FAILED: 'APPROVAL_REQUEST_REJECT_FAILED',
};

const APPROVAL_REQUEST_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

const APPROVAL_REQUEST_TYPES = {
  SCHEDULE_EXCEPTION: 'SCHEDULE_EXCEPTION',
  CANCELLATION: 'CANCELLATION',
};

const EXCEPTION_TYPES = {
  ALL_DAY: 'ALL_DAY',
  SHIFT: 'SHIFT',
  TIME_RANGE: 'TIME_RANGE',
};

const APPROVAL_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

module.exports = {
  APPROVAL_REQUEST_ROUTE_PATHS,
  APPROVAL_REQUEST_ERROR_CODES,
  APPROVAL_REQUEST_PAGINATION,
  APPROVAL_REQUEST_TYPES,
  EXCEPTION_TYPES,
  APPROVAL_STATUSES,
};
