const TIMESLOT_ROUTE_PATHS = {
  ROOT: '/',
  LOCK: '/:id/lock',
  UNLOCK: '/:id/unlock',
};

const TIMESLOT_ERROR_CODES = {
  VALIDATION_ERROR: 'TIMESLOT_VALIDATION_ERROR',
  DOCTOR_NOT_FOUND: 'TIMESLOT_DOCTOR_NOT_FOUND',
  GET_TIMESLOTS_FAILED: 'GET_TIMESLOTS_FAILED',
  NO_SCHEDULE_FOR_DATE: 'NO_SCHEDULE_FOR_DATE',
  BOOKED_SLOT_IN_EXCEPTION_SCOPE: 'BOOKED_SLOT_IN_EXCEPTION_SCOPE',
  NO_MATCHING_SLOT: 'NO_MATCHING_SLOT',
  SLOT_ALREADY_LOCKED: 'SLOT_ALREADY_LOCKED',
  LOCK_SLOT_FAILED: 'LOCK_SLOT_FAILED',
  UNLOCK_SLOT_FAILED: 'UNLOCK_SLOT_FAILED',
  SLOT_NOT_FOUND: 'SLOT_NOT_FOUND',
};

module.exports = {
  TIMESLOT_ROUTE_PATHS,
  TIMESLOT_ERROR_CODES,
};

