const BLOG_ROUTE_PATHS = {
  ROOT: '/',
  DETAIL: '/:slug',
  ADMIN_ROOT: '/admin',
  ADMIN_DETAIL: '/admin/:id',
};

const BLOG_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BLOG_NOT_FOUND: 'BLOG_NOT_FOUND',
  BLOG_SLUG_ALREADY_EXISTS: 'BLOG_SLUG_ALREADY_EXISTS',
  CREATE_BLOG_FAILED: 'CREATE_BLOG_FAILED',
  UPDATE_BLOG_FAILED: 'UPDATE_BLOG_FAILED',
  DELETE_BLOG_FAILED: 'DELETE_BLOG_FAILED',
  LIST_BLOGS_FAILED: 'LIST_BLOGS_FAILED',
  GET_BLOG_FAILED: 'GET_BLOG_FAILED',
};

const BLOG_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};

module.exports = {
  BLOG_ROUTE_PATHS,
  BLOG_ERROR_CODES,
  BLOG_PAGINATION,
};
