const CHAT_ROUTE_PATHS = {
  CONVERSATIONS: '/conversations',
  CONVERSATION_DETAIL: '/conversations/:id',
  MESSAGES: '/conversations/:id/messages',
};

const CHAT_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  UNAUTHORIZED_PARTICIPANT: 'UNAUTHORIZED_PARTICIPANT',
  INVALID_RECIPIENT: 'INVALID_RECIPIENT',
  SEND_MESSAGE_FAILED: 'SEND_MESSAGE_FAILED',
};

const CHAT_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 50,
  MAX_LIMIT: 100,
};

module.exports = {
  CHAT_ROUTE_PATHS,
  CHAT_ERROR_CODES,
  CHAT_PAGINATION,
};
